SQLx refactor core changes
azuma-chat/azumaneo pull request #5
Opened 2020-12-20 20:15 UTC by okrplay

Not all routes are refactored yet, but I made multiple changes to core files like `main.rs` and want to get those onto the dev branch to prevent merge conflicts later on in case anyone works directly on the dev branch till then. I will merge the remaining changes in a later pull request.

2020-12-20 22:09 UTC, cloudybyte commented on sqlx-data.json
> +      ],
Please add a column for the avatar url

2020-12-20 22:09 UTC, cloudybyte commented on migrations/1_create_users.sql
> +)
Please add a column for the avatar url

2020-12-20 22:13 UTC, cloudybyte requested changes
Please add the avatar url column and this thing is good to go

2020-12-20 22:37 UTC, okrplay commented
I'll add that and the other missing things in the next and final PR from `sqlx-refactor` to `dev`.

2020-12-21 17:01 UTC, okrplay commented on migrations/1_create_users.sql
> +)
I'll add that in the next and final PR from `sqlx-refactor` to `dev`.

2020-12-21 17:03 UTC, cloudybyte approved these changes
approved

2020-12-21 17:21 UTC, merged

2020-12-27 16:41 UTC, okrplay commented
The remaining user functions have been implemented in de68b1b092c81409a257a5801643350d8cefaf06 and the issue #8 has been created to keep track of the implementation of user icon and user status.